sudo: required
services:
  - docker

before_install:
  - docker build -t docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker Frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-374408092827"
  bucket_path: "Docker Frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"